### ISSUE TITLE
Inquiry about the pKa CSV file in pKPDB

### ISSUE THREAD

**Issue by honglean** [mms-fcul/PypKa#15]
Hello, I want to download the pKa CSV file, but I can't open the webpage. Do you give me some help?Thank you very much.

**Comment by pedrishi** [comment]
Hi, yesterday we had some problems with the server but today it should be running as intended. Thus, you should now be able to retrieve that file directly from the webserver.

**Comment by honglean** [comment]
Thank you very much for your response, I have successfully downloaded the data, and appreciate your openness with the data.

**Comment by honglean** [comment]
Hello, sorry to bother you again. I downloaded the pkas.csv.gz file, but when I tried using multiple decompression software, it showed that the compression file format is unknown or the data is corrupted, or the compressed file can not be found. Additionally, when I removed the .gz extension, I was able to open the CSV file, but it only shows 1048576 rows. Do you know any solutions to this issue?

**Comment by pedrishi** [comment]
Hey, that's strange... I just downloaded from the server (https://api.pypka.org/pkas.csv.gz) and unzipped with gunzip. The resulting csv file has 12628149 lines.

**Comment by honglean** [comment]
Ok, I'll try a few more times, thank you for your reply!
