### ISSUE TITLE
Installation cannot find mc

### ISSUE THREAD

**Issue by xiki-tempula** [mms-fcul/PypKa#2]
I was trying to install Pypka in osx
I have run 
```
conda create -n PypKa -python=3
conda activate PypKa
sudo port install gawk gcc gfortran libgfortran4
pip3 install pypka
```
However, I got 
```
>>> from pypka.pypka import Titration
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/XXX/opt/miniconda3/envs/PypKa/lib/python3.8/site-packages/pypka/pypka.py", line 14, in <module>
    from molecule import Molecule
  File "/Users/XXX/opt/miniconda3/envs/PypKa/lib/python3.8/site-packages/pypka/molecule.py", line 7, in <module>
    from concurrency import startPoolProcesses, runInteractionCalcs, runMCCalcs
  File "/Users/XXX/opt/miniconda3/envs/PypKa/lib/python3.8/site-packages/pypka/concurrency.py", line 7, in <module>
    from mc import MCrun
ModuleNotFoundError: No module named 'mc'
```
I was wondering if I can get help on how to solve this issue, please? Thank you.

**Comment by pedrishi** [comment]
Hi,

Unfortunately, at the moment pypka only runs on Linux or Windows via WSL. We are currently working on a cloud server where you might be able to submit your own structures (even from the API).

In the meanwhile may I suggest you either run pypka on [gcolab](https://colab.research.google.com/github/mms-fcul/PypKa/blob/master/pypka/example/notebook/pypka.ipynb) or in this [docker image](https://hub.docker.com/r/marsipan/ubuntu-pypka) made by @pjmartel

I hope this is enough to help you out, even though it is not exactly a fix.

**Comment by xiki-tempula** [comment]
Hi, thank you.
I tried to run the docker image on a ubuntu machine
docker run -it -v marsipan/ubuntu-pypka:latest
and try to run `pypka parameters.dat` according to https://pypka.readthedocs.io/en/latest/example.html
However I got 
```
root@a76b81cfbf24:/pypka# pypka parameters.dat
Traceback (most recent call last):
  File "/usr/local/bin/pypka", line 11, in <module>
    load_entry_point('pypka==1.1.0', 'console_scripts', 'pypka')()
  File "/usr/local/lib/python3.6/dist-packages/pypka/pypka.py", line 852, in CLI
    sites, parameters, debug = check_cli_args()
  File "/usr/local/lib/python3.6/dist-packages/pypka/cli.py", line 93, in check_cli_args
    raise IOError('File {0} does not exist.'.format(args.settings))
OSError: File parameters.dat does not exist.
```

**Comment by pedrishi** [comment]
Unfortunately, I was not able to reproduce your error. Please check that you have the **parameters.dat** found in the documentation.

`root@d949dfd78872:~/pypka# ls
4lzt.pdb  LOG  PypKa  example  parameters.dat

root@d949dfd78872:~/pypka# cat parameters.dat 
structure       = 4lzt.pdb
epsin           = 10
ionicstr        = 0.1
pbc_dimensions  = 0
ncpus           = 4
sites_A         = all

root@d949dfd78872:~/pypka# pypka parameters.dat 
Start Preprocessing
Start PB Calculations
...`

**Comment by xiki-tempula** [comment]
@pedrishi It seems that I cannot map the file to /pypka.
docker run -it -v ~/pypka:/pypka marsipan/ubuntu-pypka:latest
will give
```
root@2999fe8d5305:/pypka# cat parameter.dat 
structure       = 4lzt.pdb
epsin           = 10
ionicstr        = 0.1
pbc_dimensions  = 0
ncpus           = 4
sites_A         = all
root@2999fe8d5305:/pypka# pypka parameters.dat
Traceback (most recent call last):
  File "/usr/local/bin/pypka", line 11, in <module>
    load_entry_point('pypka==1.1.0', 'console_scripts', 'pypka')()
  File "/usr/local/lib/python3.6/dist-packages/pypka/pypka.py", line 852, in CLI
    sites, parameters, debug = check_cli_args()
  File "/usr/local/lib/python3.6/dist-packages/pypka/cli.py", line 93, in check_cli_args
    raise IOError('File {0} does not exist.'.format(args.settings))
OSError: File parameters.dat does not exist.
```

However, mapping it to other things like work fine.
`docker run -it -v ~/pypka:/test marsipan/ubuntu-pypka:latest`
